name: Generate Docs on PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checking out repository
        uses: actions/checkout@v2

      - name: Generate architecture diagram
        run: make architecture

      - name: Generate other diagram with mermaid js
        run: make mermaid-diagram

      - name: Get generated files
        id: getgenerated
        run: |
          echo "::set-output name=files::$(find docs/out -type f -name '*' |xargs echo)"

      - uses: actions/upload-artifact@v1
        with:
          name: generated-diagram
          path: docs/out

      - name: add artifact links to pull request and related issues step
        uses: tonyhallett/artifacts-url-comments@v1.1.0
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            prefix: Here are the artifacts 
            suffix: Have a nice day.
            addTo: pull