name: Generate Docs on PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repository
        uses: actions/checkout@v2

      - name: Generate architecture diagram
        run: make architecture

      - name: Generate other diagram with mermaid js
        run: make mermaid-diagram

      - name: Get generated files
        id: getgenerated
        run: |
          echo "::set-output name=files::$(find docs/out -type f -name '*' |xargs echo)"

      - name: show diagram on PR comment
        uses: KeisukeYamashita/create-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          unique: true
          check-only-first-line: true
          comment: |
            ${{ steps.getgenerated.outputs.files }}