name: Generating Docs

on:
  push:
    branches:
      - master
    paths:
      - 'docs/*.mmd'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repository
        uses: actions/checkout@v2

      - name: Get files
        id: getfiles
        uses: Rishabh510/Path-lister-action@master
        with:
          path: "docs"
          type: ".mmd"

      - name: files to be compiled
        run: |
          echo ${{ steps.getfiles.outputs.paths }}

      - name: compile mermaid
        uses: neenjaw/compile-mermaid-markdown-action@v0.3.3
        with:
          files: ${{ steps.getfiles.outputs.paths }}
          output: 'output'
        env:
          HIDE_CODEBLOCKS: 1
          ABSOLUTE_IMAGE_LINKS: 1
          OUTPUT_FILE_TYPE: "svg"

      - name: Get Generated Files
        id: getsvg
        uses: Rishabh510/Path-lister-action@master
        with:
          path: "output"
          type: ".svg"

      - name: diagram generated
        run: |
          echo ${{ steps.getsvg.outputs.paths }}
      
      - name: push to system-diagram
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'output'
          destination_branch: 'master'
          destination_repo: 'ardityawahyu/lemon'
          destination_folder: 'test-dir'
          user_email: 'wahyu.arditya@gmail.com'
          user_name: 'ardityawahyu'
          commit_message: 'testing push from another repo via actions'
          