name: Generating Docs

on:
  push:
    branches:
      - master
    paths:
      - 'docs/*.mmd'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repository
        uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
        
      - name: Generating docs
        run: |
          npm install 
          npm test
          npm install @mermaid-js/mermaid-cli
          make mermaid